apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-auditor-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: default
